
import { RecordType, MasterSetting } from './types';

export const DEFAULT_MASTER_SETTINGS: MasterSetting[] = [
  {
    id: '1',
    recordType: RecordType.EXPENSE,
    mainCategory: 'Rent',
    subCategory: 'House Rent',
    paymentMode: 'Bank Transfer',
    accountCard: 'SBI Account',
    monthlyCap: 25000,
    active: true,
  },
  {
    id: '2',
    recordType: RecordType.EXPENSE,
    mainCategory: 'EMI',
    subCategory: 'Home EMI',
    paymentMode: 'Bank Transfer',
    accountCard: 'HDFC Loan',
    monthlyCap: 40000,
    active: true,
  },
  {
    id: '3',
    recordType: RecordType.EXPENSE,
    mainCategory: 'Food',
    subCategory: 'Groceries',
    paymentMode: 'UPI',
    accountCard: 'GPay',
    monthlyCap: 12000,
    active: true,
  },
  {
    id: '4',
    recordType: RecordType.EXPENSE,
    mainCategory: 'Food',
    subCategory: 'Dining Out',
    paymentMode: 'Credit Card',
    accountCard: 'HDFC CC',
    monthlyCap: 12000,
    active: true,
  },
  {
    id: '5',
    recordType: RecordType.EXPENSE,
    mainCategory: 'Fuel',
    subCategory: 'Petrol',
    paymentMode: 'Credit Card',
    accountCard: 'HDFC CC',
    monthlyCap: 5000,
    active: true,
  },
  {
    id: '6',
    recordType: RecordType.EXPENSE,
    mainCategory: 'Utilities',
    subCategory: 'Electricity',
    paymentMode: 'UPI',
    accountCard: 'PhonePe',
    monthlyCap: 4000,
    active: true,
  },
  {
    id: '7',
    recordType: RecordType.EXPENSE,
    mainCategory: 'Credit Card',
    subCategory: 'CC Bill',
    paymentMode: 'Credit Card',
    accountCard: 'HDFC CC',
    monthlyCap: 15000,
    active: true,
  },
  {
    id: '8',
    recordType: RecordType.INCOME,
    mainCategory: 'Salary',
    subCategory: 'Monthly Salary',
    paymentMode: 'Bank Transfer',
    accountCard: 'Salary A/c',
    monthlyCap: 0,
    active: true,
  },
  {
    id: '9',
    recordType: RecordType.INVESTMENT,
    mainCategory: 'MF',
    subCategory: 'Index Fund',
    paymentMode: 'Bank Transfer',
    accountCard: 'Coin',
    monthlyCap: 0,
    active: true,
  },
];
